# Generated by Django 4.2.30 on 2026-06-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kontrahenci', '0003_uzytkownikpojazdu'),
        ('pojazdy', '0010_pojazd_data_pierwszej_rejestracji_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZlecenieSerwisowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_trakcie_wynajmu', models.BooleanField(default=False, verbose_name='W trakcie wynajmu')),
                ('platnik', models.CharField(choices=[('srodki_wlasne', 'Środki własne'), ('gwarancja', 'Gwarancja'), ('wlasciciel', 'Właściciel pojazdu'), ('leasing', 'Leasing')], max_length=20)),
                ('typ', models.CharField(choices=[('przeglad', 'Przegląd'), ('naprawa', 'Naprawa'), ('opony', 'Opony'), ('holowanie', 'Holowanie'), ('samochod_zastepczy', 'Samochód zastępczy'), ('inne', 'Inne')], max_length=30)),
                ('status', models.CharField(choices=[('otwarte', 'Otwarte'), ('w_realizacji', 'W realizacji'), ('zamkniete', 'Zamknięte'), ('anulowane', 'Anulowane')], default='otwarte', max_length=20)),
                ('data_przyjecia', models.DateField()),
                ('planowana_data_zakonczenia', models.DateField(blank=True, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('planowany_koszt_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rzeczywisty_koszt_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('przebieg', models.IntegerField(blank=True, null=True)),
                ('najemca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zlecenia_jako_najemca', to='kontrahenci.kontrahent', verbose_name='Najemca')),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zlecenia_serwisowe', to='pojazdy.pojazd')),
                ('warsztat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zlecenia_jako_warsztat', to='kontrahenci.kontrahent', verbose_name='Warsztat')),
            ],
            options={
                'verbose_name': 'Zlecenie serwisowe',
                'verbose_name_plural': 'Zlecenia serwisowe',
            },
        ),
        migrations.CreateModel(
            name='Uszkodzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wykrycia', models.DateField(auto_now_add=True)),
                ('opis', models.TextField()),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='uszkodzenia/')),
                ('zglaszajacy', models.CharField(blank=True, max_length=100, null=True)),
                ('naprawione', models.BooleanField(default=False)),
                ('koszt_naprawy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uszkodzenia', to='pojazdy.pojazd')),
            ],
            options={
                'verbose_name': 'Uszkodzenie',
                'verbose_name_plural': 'Uszkodzenia',
            },
        ),
        migrations.CreateModel(
            name='SzkodaBladcharska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_trakcie_wynajmu', models.BooleanField(default=False, verbose_name='W trakcie wynajmu')),
                ('platnik', models.CharField(choices=[('srodki_wlasne', 'Środki własne'), ('ac', 'AC'), ('oc_sprawcy', 'OC sprawcy')], max_length=20)),
                ('numer_szkody', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('zgloszona', 'Zgłoszona'), ('w_realizacji', 'W realizacji'), ('zamknieta', 'Zamknięta'), ('anulowana', 'Anulowana')], default='zgloszona', max_length=20)),
                ('planowany_koszt_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rzeczywisty_koszt_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('przebieg', models.IntegerField(blank=True, null=True)),
                ('data_zdarzenia', models.DateField(blank=True, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('najemca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='szkody_jako_najemca', to='kontrahenci.kontrahent', verbose_name='Najemca')),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='szkody', to='pojazdy.pojazd')),
                ('warsztat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='szkody_jako_warsztat', to='kontrahenci.kontrahent', verbose_name='Warsztat')),
            ],
            options={
                'verbose_name': 'Szkoda blacharska',
                'verbose_name_plural': 'Szkody blacharskie',
            },
        ),
    ]
