# Generated by Django 4.2.30 on 2026-08-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='szkodabladcharska',
            options={'ordering': ['-data_zdarzenia', '-pk'], 'verbose_name': 'Szkoda blacharska', 'verbose_name_plural': 'Szkody blacharskie'},
        ),
        migrations.AlterModelOptions(
            name='uszkodzenie',
            options={'ordering': ['-data_wykrycia', '-pk'], 'verbose_name': 'Uszkodzenie', 'verbose_name_plural': 'Uszkodzenia'},
        ),
        migrations.AlterModelOptions(
            name='zlecenieserwisowe',
            options={'ordering': ['-data_przyjecia', '-pk'], 'verbose_name': 'Zlecenie serwisowe', 'verbose_name_plural': 'Zlecenia serwisowe'},
        ),
    ]
