# Generated by Django 4.2.30 on 2026-06-06 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontrahent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stan', models.CharField(choices=[('aktywny', 'Aktywny'), ('nieaktywny', 'Nieaktywny')], default='aktywny', max_length=20)),
                ('typ', models.CharField(choices=[('klient', 'Klient'), ('broker', 'Broker'), ('dealer', 'Dealer'), ('dostawca_finansowania', 'Dostawca finansowania'), ('obsluga_serwisowa', 'Obsługa serwisowa'), ('serwis', 'Serwis'), ('wlasciciel_pojazdow', 'Właściciel pojazdów')], max_length=30)),
                ('nazwa_firmy', models.CharField(max_length=200)),
                ('rodzaj_dzialalnosci', models.CharField(blank=True, choices=[('sp_zoo', 'Sp. z o.o.'), ('sa', 'S.A.'), ('jdg', 'Jednoosobowa działalność gospodarcza'), ('spolka_jawna', 'Spółka jawna'), ('spolka_komandytowa', 'Spółka komandytowa'), ('inne', 'Inne')], max_length=30, null=True)),
                ('nip', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('regon', models.CharField(blank=True, max_length=14, null=True)),
                ('numer_krs', models.CharField(blank=True, max_length=10, null=True)),
                ('kod_kraj', models.CharField(default='PL', max_length=3)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_faktury', models.EmailField(blank=True, max_length=254, null=True)),
                ('ulica', models.CharField(blank=True, max_length=100, null=True)),
                ('numer_domu', models.CharField(blank=True, max_length=10, null=True)),
                ('numer_mieszkania', models.CharField(blank=True, max_length=10, null=True)),
                ('kod_pocztowy', models.CharField(blank=True, max_length=10, null=True)),
                ('miasto', models.CharField(blank=True, max_length=100, null=True)),
                ('wojewodztwo', models.CharField(blank=True, max_length=50, null=True)),
                ('kraj', models.CharField(default='Polska', max_length=50)),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('opiekun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kontrahenci', to=settings.AUTH_USER_MODEL, verbose_name='Opiekun klienta')),
            ],
            options={
                'verbose_name': 'Kontrahent',
                'verbose_name_plural': 'Kontrahenci',
            },
        ),
        migrations.CreateModel(
            name='DodatkoweDaneKontaktowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('telefon', 'Telefon'), ('email', 'Email'), ('fax', 'Fax'), ('inne', 'Inne')], max_length=20)),
                ('wartosc', models.CharField(max_length=100)),
                ('opis', models.CharField(blank=True, max_length=100, null=True)),
                ('kontrahent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodatkowe_kontakty', to='kontrahenci.kontrahent')),
            ],
            options={
                'verbose_name': 'Dodatkowe dane kontaktowe',
                'verbose_name_plural': 'Dodatkowe dane kontaktowe',
            },
        ),
    ]
