# Generated by Django 4.2.30 on 2026-06-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrahenci', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontrahent',
            name='typ',
        ),
        migrations.AddField(
            model_name='kontrahent',
            name='typ_broker',
            field=models.BooleanField(default=False, verbose_name='Broker'),
        ),
        migrations.AddField(
            model_name='kontrahent',
            name='typ_dealer',
            field=models.BooleanField(default=False, verbose_name='Dealer'),
        ),
        migrations.AddField(
            model_name='kontrahent',
            name='typ_dostawca_finansowania',
            field=models.BooleanField(default=False, verbose_name='Dostawca finansowania'),
        ),
        migrations.AddField(
            model_name='kontrahent',
            name='typ_klient',
            field=models.BooleanField(default=False, verbose_name='Klient'),
        ),
        migrations.AddField(
            model_name='kontrahent',
            name='typ_obsluga_serwisowa',
            field=models.BooleanField(default=False, verbose_name='Obsługa serwisowa'),
        ),
        migrations.AddField(
            model_name='kontrahent',
            name='typ_serwis',
            field=models.BooleanField(default=False, verbose_name='Serwis'),
        ),
        migrations.AddField(
            model_name='kontrahent',
            name='typ_wlasciciel_pojazdow',
            field=models.BooleanField(default=False, verbose_name='Właściciel pojazdów'),
        ),
    ]
