# Generated by Django 4.2.30 on 2026-06-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrahenci', '0002_remove_kontrahent_typ_kontrahent_typ_broker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UzytkownikPojazdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pesel', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('ulica', models.CharField(blank=True, max_length=100, null=True)),
                ('numer_domu', models.CharField(blank=True, max_length=10, null=True)),
                ('numer_mieszkania', models.CharField(blank=True, max_length=10, null=True)),
                ('kod_pocztowy', models.CharField(blank=True, max_length=10, null=True)),
                ('miasto', models.CharField(blank=True, max_length=100, null=True)),
                ('kraj', models.CharField(default='Polska', max_length=50)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('numer_dokumentu', models.CharField(blank=True, max_length=20, null=True)),
                ('numer_prawa_jazdy', models.CharField(blank=True, max_length=20, null=True)),
                ('data_waznosci_prawa_jazdy', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Użytkownik pojazdu',
                'verbose_name_plural': 'Użytkownicy pojazdów',
            },
        ),
    ]
