# Generated by Django 4.2.30 on 2026-05-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konfiguracja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wersja_wyposazenia', models.CharField(max_length=50)),
                ('liczba_drzwi', models.IntegerField(default=5)),
                ('pojemnosc_silnika', models.CharField(max_length=20)),
                ('moc_km', models.IntegerField()),
                ('rodzaj_paliwa', models.CharField(choices=[('benzyna', 'Benzyna'), ('diesel', 'Diesel'), ('hybryda', 'Hybryda'), ('elektryk', 'Elektryk')], max_length=20)),
                ('spalanie_l100km', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('co2_gkm', models.IntegerField(blank=True, null=True)),
                ('interwał_przeglądu_km', models.IntegerField(default=15000)),
                ('interwał_przeglądu_miesięcy', models.IntegerField(default=12)),
            ],
            options={
                'verbose_name': 'Konfiguracja',
                'verbose_name_plural': 'Konfiguracje',
            },
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marki',
            },
        ),
        migrations.CreateModel(
            name='Pojazd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_rejestracyjny', models.CharField(max_length=20, unique=True)),
                ('rok_produkcji', models.IntegerField()),
                ('data_zakupu', models.DateField()),
                ('przebieg_km', models.IntegerField(default=0)),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('status', models.CharField(choices=[('dostepny', 'Dostępny'), ('wynajety', 'Wynajęty'), ('serwis', 'W serwisie')], default='dostepny', max_length=20)),
                ('data_przegladu', models.DateField(blank=True, null=True)),
                ('data_ubezpieczenia', models.DateField(blank=True, null=True)),
                ('konfiguracja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pojazdy', to='pojazdy.konfiguracja')),
            ],
            options={
                'verbose_name': 'Pojazd',
                'verbose_name_plural': 'Pojazdy',
            },
        ),
        migrations.CreateModel(
            name='ModelPojazdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modele', to='pojazdy.marka')),
            ],
            options={
                'verbose_name': 'Model pojazdu',
                'verbose_name_plural': 'Modele pojazdów',
            },
        ),
        migrations.AddField(
            model_name='konfiguracja',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konfiguracje', to='pojazdy.modelpojazdu'),
        ),
    ]
