# Generated by Django 4.2.30 on 2026-06-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojazdy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='konfiguracja',
            name='maksymalna_liczba_pasazerow',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='konfiguracja',
            name='moc_kw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='konfiguracja',
            name='naped',
            field=models.CharField(choices=[('fwd', 'Przednie koła'), ('rwd', 'Tylne koła'), ('awd', 'Wszystkie koła')], default='fwd', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='konfiguracja',
            name='pojemnosc_baku',
            field=models.IntegerField(blank=True, help_text='Litry', null=True),
        ),
        migrations.AddField(
            model_name='konfiguracja',
            name='typ_nadwozia',
            field=models.CharField(choices=[('kombi', 'Kombi'), ('suv', 'SUV'), ('crossover', 'Crossover'), ('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('limuzyna', 'Limuzyna'), ('van', 'Van'), ('bus', 'Bus')], default='sedan', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='konfiguracja',
            name='typ_skrzyni',
            field=models.CharField(choices=[('manualna', 'Manualna'), ('automatyczna', 'Automatyczna')], default='manualna', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='konfiguracja',
            name='rodzaj_paliwa',
            field=models.CharField(choices=[('benzyna', 'Benzyna'), ('diesel', 'Diesel'), ('hybryda', 'Hybryda'), ('elektryk', 'Elektryk'), ('benzyna_lpg', 'Benzyna z LPG')], max_length=20),
        ),
    ]
