# Generated by Django 4.2.30 on 2026-06-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojazdy', '0002_konfiguracja_maksymalna_liczba_pasazerow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('oc', 'OC'), ('ac', 'AC'), ('oc_ac', 'OC + AC'), ('nnw', 'NNW'), ('assistance', 'Assistance')], max_length=20)),
                ('numer_umowy_generalnej', models.CharField(blank=True, max_length=50, null=True)),
                ('numer_polisy', models.CharField(max_length=50, unique=True)),
                ('data_od', models.DateField()),
                ('data_do', models.DateField(blank=True, null=True)),
                ('ubezpieczyciel', models.CharField(blank=True, max_length=100, null=True)),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('skan', models.FileField(blank=True, null=True, upload_to='polisy/')),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polisy', to='pojazdy.pojazd')),
            ],
            options={
                'verbose_name': 'Polisa',
                'verbose_name_plural': 'Polisy',
            },
        ),
    ]
