# Generated by Django 4.2.30 on 2026-06-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojazdy', '0003_polisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='dostawca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pojazd',
            name='oddzial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pojazd',
            name='stan',
            field=models.CharField(choices=[('w_przygotowaniu', 'W przygotowaniu'), ('w_eksploatacji', 'W eksploatacji'), ('wylaczony', 'Wyłączony z eksploatacji'), ('do_wycofania', 'Do wycofania')], default='w_przygotowaniu', max_length=20),
        ),
        migrations.AddField(
            model_name='pojazd',
            name='wlasciciel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pojazd',
            name='wspolwlasciciel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
