# Generated by Django 4.2.30 on 2026-06-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrahenci', '0001_initial'),
        ('pojazdy', '0004_pojazd_dostawca_pojazd_oddzial_pojazd_stan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojazd',
            name='dostawca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pojazdy_dostarczone', to='kontrahenci.kontrahent'),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='wlasciciel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pojazdy_wlasne', to='kontrahenci.kontrahent'),
        ),
        migrations.AlterField(
            model_name='pojazd',
            name='wspolwlasciciel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pojazdy_wspolwlasne', to='kontrahenci.kontrahent'),
        ),
    ]
