# Generated by Django 4.2.30 on 2026-06-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wynajmy', '0001_initial'),
        ('pojazdy', '0005_alter_pojazd_dostawca_alter_pojazd_wlasciciel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='konfiguracja',
            name='klasa_pojazdu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wynajmy.klasapojazdu', verbose_name='Klasa pojazdu'),
        ),
    ]
