# Generated by Django 4.2.30 on 2026-06-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojazdy', '0006_konfiguracja_klasa_pojazdu'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlasaPojazdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Klasa pojazdu',
                'verbose_name_plural': 'Klasy pojazdów',
            },
        ),
        migrations.AlterField(
            model_name='konfiguracja',
            name='klasa_pojazdu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pojazdy.klasapojazdu', verbose_name='Klasa pojazdu'),
        ),
    ]
