# Generated by Django 4.2.30 on 2026-06-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojazdy', '0007_klasapojazdu_alter_konfiguracja_klasa_pojazdu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='id_pojazdu',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
