# Generated by Django 4.2.30 on 2026-06-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojazdy', '0008_pojazd_id_pojazdu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polisa',
            name='rodzaj',
        ),
        migrations.AddField(
            model_name='polisa',
            name='rodzaj_ac',
            field=models.BooleanField(default=False, verbose_name='AC'),
        ),
        migrations.AddField(
            model_name='polisa',
            name='rodzaj_assistance',
            field=models.BooleanField(default=False, verbose_name='Assistance'),
        ),
        migrations.AddField(
            model_name='polisa',
            name='rodzaj_nnw',
            field=models.BooleanField(default=False, verbose_name='NNW'),
        ),
        migrations.AddField(
            model_name='polisa',
            name='rodzaj_oc',
            field=models.BooleanField(default=False, verbose_name='OC'),
        ),
    ]
