# Generated by Django 4.2.30 on 2026-06-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojazdy', '0009_remove_polisa_rodzaj_polisa_rodzaj_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojazd',
            name='data_pierwszej_rejestracji',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pojazd',
            name='lata_gwarancji',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gwarancja (lata)'),
        ),
    ]
