# Generated by Django 4.2.30 on 2026-06-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pojazdy', '0005_alter_pojazd_dostawca_alter_pojazd_wlasciciel_and_more'),
        ('kontrahenci', '0002_remove_kontrahent_typ_kontrahent_typ_broker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cennik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('typ_stawki', models.CharField(choices=[('dzienna', 'Dzienna'), ('tygodniowa', 'Tygodniowa'), ('miesieczna', 'Miesięczna')], max_length=20)),
                ('waluta', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR')], default='PLN', max_length=3)),
                ('aktywny', models.BooleanField(default=True)),
                ('kontrahent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cenniki', to='kontrahenci.kontrahent', verbose_name='Firma (puste = standardowy)')),
            ],
            options={
                'verbose_name': 'Cennik',
                'verbose_name_plural': 'Cenniki',
            },
        ),
        migrations.CreateModel(
            name='KlasaPojazdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Klasa pojazdu',
                'verbose_name_plural': 'Klasy pojazdów',
            },
        ),
        migrations.CreateModel(
            name='UzytkownikPojazdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pesel', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('ulica', models.CharField(blank=True, max_length=100, null=True)),
                ('numer_domu', models.CharField(blank=True, max_length=10, null=True)),
                ('numer_mieszkania', models.CharField(blank=True, max_length=10, null=True)),
                ('kod_pocztowy', models.CharField(blank=True, max_length=10, null=True)),
                ('miasto', models.CharField(blank=True, max_length=100, null=True)),
                ('kraj', models.CharField(default='Polska', max_length=50)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('numer_dokumentu', models.CharField(blank=True, max_length=20, null=True)),
                ('numer_prawa_jazdy', models.CharField(blank=True, max_length=20, null=True)),
                ('data_waznosci_prawa_jazdy', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Użytkownik pojazdu',
                'verbose_name_plural': 'Użytkownicy pojazdów',
            },
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nowa', 'Nowa'), ('potwierdzona', 'Potwierdzona'), ('w_toku', 'W toku'), ('zakonczona', 'Zakończona'), ('anulowana', 'Anulowana')], default='nowa', max_length=20)),
                ('typ', models.CharField(choices=[('corpo', 'Corpo'), ('konsumencki', 'Wynajem konsumencki')], max_length=20)),
                ('waluta', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR')], default='PLN', max_length=3)),
                ('mpk_klienta', models.CharField(blank=True, max_length=50, null=True)),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('uwagi_faktura', models.TextField(blank=True, null=True)),
                ('cena_jednostkowa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('planowana_data_wydania', models.DateTimeField()),
                ('oddzial_wydania', models.CharField(blank=True, max_length=100, null=True)),
                ('adres_podstawienia', models.CharField(blank=True, max_length=200, null=True)),
                ('podstawienie', models.BooleanField(default=False)),
                ('planowana_data_zwrotu', models.DateTimeField()),
                ('taki_sam_adres_zwrotu', models.BooleanField(default=True)),
                ('adres_zwrotu', models.CharField(blank=True, max_length=200, null=True)),
                ('uwagi_zwrot', models.TextField(blank=True, null=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
                ('cennik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rezerwacje', to='wynajmy.cennik')),
                ('klasa_pojazdu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rezerwacje', to='wynajmy.klasapojazdu')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rezerwacje', to='kontrahenci.kontrahent')),
                ('pojazd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rezerwacje', to='pojazdy.pojazd')),
                ('uzytkownik_pojazdu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rezerwacje', to='wynajmy.uzytkownikpojazdu')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
            },
        ),
        migrations.CreateModel(
            name='PozycjaCennika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cennik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='wynajmy.cennik')),
                ('klasa_pojazdu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pozycje_cennika', to='wynajmy.klasapojazdu')),
            ],
            options={
                'verbose_name': 'Pozycja cennika',
                'verbose_name_plural': 'Pozycje cennika',
                'unique_together': {('cennik', 'klasa_pojazdu')},
            },
        ),
    ]
