# Generated by Django 4.2.30 on 2026-06-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojazdy', '0007_klasapojazdu_alter_konfiguracja_klasa_pojazdu'),
        ('wynajmy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozycjacennika',
            name='klasa_pojazdu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pozycje_cennika', to='pojazdy.klasapojazdu'),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='klasa_pojazdu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rezerwacje', to='pojazdy.klasapojazdu'),
        ),
        migrations.DeleteModel(
            name='KlasaPojazdu',
        ),
    ]
