# Generated by Django 4.2.30 on 2026-07-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrahenci', '0003_uzytkownikpojazdu'),
        ('wynajmy', '0002_alter_pozycjacennika_klasa_pojazdu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacja',
            name='uzytkownik_pojazdu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rezerwacje', to='kontrahenci.uzytkownikpojazdu'),
        ),
        migrations.DeleteModel(
            name='UzytkownikPojazdu',
        ),
    ]
