# Generated by Django 4.2.30 on 2026-07-27 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojazdy', '0011_pojazd_oddzial_fk'),
        ('wynajmy', '0003_alter_rezerwacja_uzytkownik_pojazdu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZmianaPojazdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zamiany', models.DateTimeField(verbose_name='Data zamiany')),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zmiany_rezerwacji', to='pojazdy.pojazd')),
                ('rezerwacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zmiany_pojazdu', to='wynajmy.rezerwacja')),
            ],
            options={
                'verbose_name': 'Zamiana pojazdu',
                'verbose_name_plural': 'Zamiany pojazdów',
                'ordering': ['data_zamiany'],
            },
        ),
    ]
