# Generated by Django 4.2.30 on 2026-08-19 21:02

from django.db import migrations, models


def nadaj_numery(apps, schema_editor):
    """Nadaje numery istniejacym rezerwacjom przed zalozeniem unikalnosci."""
    Rezerwacja = apps.get_model('wynajmy', 'Rezerwacja')
    licznik = {}
    for r in Rezerwacja.objects.filter(numer='').order_by('pk'):
        rok = r.data_utworzenia.year if r.data_utworzenia else 2026
        licznik[rok] = licznik.get(rok, 0) + 1
        r.numer = f'REZ/{rok}/{licznik[rok]:03d}'
        r.save(update_fields=['numer'])


class Migration(migrations.Migration):

    dependencies = [
        ('wynajmy', '0004_zmianapojazdu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezerwacja',
            options={'ordering': ['-planowana_data_wydania'], 'verbose_name': 'Rezerwacja', 'verbose_name_plural': 'Rezerwacje'},
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='faktyczna_data_wydania',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='faktyczna_data_zwrotu',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='numer',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
        migrations.RunPython(nadaj_numery, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='rezerwacja',
            name='numer',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='przebieg_wydania',
            field=models.IntegerField(blank=True, null=True, verbose_name='Przebieg przy wydaniu (km)'),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='przebieg_zwrotu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Przebieg przy zwrocie (km)'),
        ),
    ]
