from django.urls import path
from . import views

urlpatterns = [
    path('pojazdy/', views.pojazdy, name='pojazdy'),
    path('pojazdy/dodaj/', views.dodaj_pojazd, name='dodaj_pojazd'),
    path('pojazdy/<int:pk>/', views.pojazd_szczegoly, name='pojazd_szczegoly'),
    path('pojazdy/<int:pk>/edytuj/', views.edytuj_pojazd, name='edytuj_pojazd'),
    path('pojazdy/<int:pk>/zmien-stan/', views.zmien_stan_pojazdu, name='zmien_stan_pojazdu'),
    path('polisy/', views.polisy, name='polisy'),
    path('polisy/dodaj/', views.dodaj_polise, name='dodaj_polise'),
    path('polisy/<int:pk>/', views.polisa_szczegoly, name='polisa_szczegoly'),
    path('polisy/<int:pk>/edytuj/', views.edytuj_polise, name='edytuj_polise'),
    path('marki/', views.marki, name='marki'),
    path('marki/dodaj/', views.dodaj_marke, name='dodaj_marke'),
    path('marki/<int:pk>/', views.marka_szczegoly, name='marka_szczegoly'),
    path('marki/<int:pk>/edytuj/', views.edytuj_marke, name='edytuj_marke'),
    path('modele/', views.modele, name='modele'),
    path('modele/dodaj/', views.dodaj_model, name='dodaj_model'),
    path('modele/<int:pk>/', views.model_szczegoly, name='model_szczegoly'),
    path('modele/<int:pk>/edytuj/', views.edytuj_model, name='edytuj_model'),
    path('klasy/', views.klasy, name='klasy'),
    path('klasy/dodaj/', views.dodaj_klase, name='dodaj_klase'),
    path('klasy/<int:pk>/', views.klasa_szczegoly, name='klasa_szczegoly'),
    path('klasy/<int:pk>/edytuj/', views.edytuj_klase, name='edytuj_klase'),
    path('konfiguracje/', views.konfiguracje, name='konfiguracje'),
    path('konfiguracje/dodaj/', views.dodaj_konfiguracje, name='dodaj_konfiguracje'),
    path('konfiguracje/<int:pk>/', views.konfiguracja_szczegoly, name='konfiguracja_szczegoly'),
    path('konfiguracje/<int:pk>/edytuj/', views.edytuj_konfiguracje, name='edytuj_konfiguracje'),
]