# Generated by Django 4.2.30 on 2026-07-25 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UkladTabeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.CharField(max_length=50)),
                ('nazwa', models.CharField(max_length=100)),
                ('dane', models.JSONField()),
                ('aktywny', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uklady_tabel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Układ tabeli',
                'verbose_name_plural': 'Układy tabel',
                'unique_together': {('user', 'tabela', 'nazwa')},
            },
        ),
    ]
