# Generated by Django 4.2.30 on 2026-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0002_ukladtabeli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oddzial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('adres', models.CharField(blank=True, max_length=200, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Oddział',
                'verbose_name_plural': 'Oddziały',
                'ordering': ['nazwa'],
            },
        ),
    ]
