# Generated by Django 4.2.30 on 2026-08-19 21:47

from django.db import migrations, models
import django.db.models.deletion


def uzupelnij_profile(apps, schema_editor):
    """Kazde istniejace konto dostaje profil; superuser zostaje administratorem.

    Bez tego uzytkownicy sprzed wdrozenia rol nie mieliby zadnej roli.
    """
    User = apps.get_model('auth', 'User')
    ProfilUzytkownika = apps.get_model('administracja', 'ProfilUzytkownika')
    for user in User.objects.all():
        rola = 'administrator' if user.is_superuser else 'pracownik'
        profil = ProfilUzytkownika.objects.filter(user=user).first()
        if profil is None:
            ProfilUzytkownika.objects.create(user=user, rola=rola)
        else:
            profil.rola = rola
            profil.save(update_fields=['rola'])


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0003_oddzial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiluzytkownika',
            name='oddzial',
            field=models.ForeignKey(blank=True, help_text='Puste = dostęp do danych wszystkich oddziałów.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzytkownicy', to='administracja.oddzial', verbose_name='Oddział'),
        ),
        migrations.AddField(
            model_name='profiluzytkownika',
            name='rola',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('kierownik', 'Kierownik'), ('pracownik', 'Pracownik'), ('podglad', 'Podgląd')], default='pracownik', max_length=20),
        ),
        migrations.RunPython(uzupelnij_profile, migrations.RunPython.noop),
    ]
